import { RemovalPolicy, Duration } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ecr from 'aws-cdk-lib/aws-ecr';

export interface EcrConstructProps {
  /**
   * Optional repository name. If not provided, a name will be generated by CDK.
   */
  repositoryName: string;
  /**
   * Whether to destroy the repository when the construct is removed.
   * Defaults to false (RETAIN).
   */
  destroyOnDelete?: boolean;
}

export class EcrConstruct extends Construct {
  public readonly repository: ecr.Repository;

  constructor(scope: Construct, id: string, props: EcrConstructProps) {
    super(scope, id);

    const { repositoryName } = props;

    this.repository = new ecr.Repository(this, 'Repository', {
      repositoryName,
      removalPolicy: props.destroyOnDelete
        ? RemovalPolicy.DESTROY
        : RemovalPolicy.RETAIN,
      lifecycleRules: [
        {
          description: 'Expire untagged images after 30 days',
          tagStatus: ecr.TagStatus.UNTAGGED,
          maxImageAge: Duration.days(30),
        },
        {
          description: 'Keep only the 10 most recent images',
          maxImageCount: 10,
        },
      ],
    });
  }
}
