import { Stack, StackProps, RemovalPolicy, Duration } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as iam from 'aws-cdk-lib/aws-iam';
import { EcrConstruct } from './constructs/ecr-repo';

export interface EcrStackProps extends StackProps {
  /**
   * Optional repository name. If not provided, a name will be generated by CDK.
   */
  repositoryNames: string[];
  /**
   * Whether to destroy the repository when the stack is deleted.
   * Defaults to false (RETAIN).
   */
  destroyOnDelete?: boolean;
}

export class EcrStack extends Stack {
  public readonly repository: ecr.Repository;

  constructor(scope: Construct, id: string, props: EcrStackProps) {
    super(scope, id, props);

    // user to push images
    const pushUser = new iam.User(this, 'EcrImagePushUser', {
      userName: 'ecr-image-pusher',
    });
    const repoPolicy = new iam.Policy(this, 'EcrPushPolicy', {});
    repoPolicy.attachToUser(pushUser);

    props.repositoryNames.forEach((repositoryName) => {
      const repo = new EcrConstruct(this, `EcrRepo-${repositoryName}`, {
        repositoryName,
        destroyOnDelete: props.destroyOnDelete,
      });
      repo.repository.grantPush(repoPolicy);
    });
  }
}
