import { Stack, StackProps, RemovalPolicy, Duration } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ecr from 'aws-cdk-lib/aws-ecr';

export interface EcrStackProps extends StackProps {
  /**
   * Optional repository name. If not provided, a name will be generated by CDK.
   */
  repositoryName?: string;
  /**
   * Whether to destroy the repository when the stack is deleted.
   * Defaults to false (RETAIN).
   */
  destroyOnDelete?: boolean;
}

export class EcrStack extends Stack {
  public readonly repository: ecr.Repository;

  constructor(scope: Construct, id: string, props: EcrStackProps = {}) {
    super(scope, id, props);

    const repositoryName = props.repositoryName ?? 'video-clips-repo';

    this.repository = new ecr.Repository(this, 'Repository', {
      repositoryName,
      removalPolicy: props.destroyOnDelete
        ? RemovalPolicy.DESTROY
        : RemovalPolicy.RETAIN,
      lifecycleRules: [
        {
          description: 'Expire untagged images after 30 days',
          tagStatus: ecr.TagStatus.UNTAGGED,
          maxImageAge: Duration.days(30),
        },
        {
          description: 'Keep only the 10 most recent images',
          maxImageCount: 10,
        },
      ],
    });
  }
}
